[build]
  base = "frontend"
  publish = "frontend/build"
  command = "npm run build"

[build.environment]
  REACT_APP_API_BASE = "https://fusionai-job-search.netlify.app/api"
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
